config/routes.rb
Filmsouseries::Application.routes.draw do

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	get '/logout' => 'sessions#destroy'

	get '/signup' => 'users#new'
	post '/users' => 'users#create'
end

Rails.application.routes.draw do
  resources :series
  get '/series/:id/set_checked/:checked' => 'series#set_checked'
  resources :films
  get '/films/:id/set_checked/:checked' => 'films#set_checked'
  resources :documentaires
  get '/documentaires/:id/set_checked/:checked' => 'documentaires#set_checked'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/documentaire.rb
# == Schema Information
#
# Table name: documentaires
#
#  id          :integer          not null, primary key
#  nom         :string
#  realisateur :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Documentaire < ApplicationRecord
end

app/controllers/documentaires_controller.rb
class DocumentairesController < ApplicationController
  before_action :set_documentaire, only: [:show, :edit, :update, :destroy, :set_checked]
  before_action :authorize

  # GET /documentaires
  # GET /documentaires.json
  def index
    @documentaires = Documentaire.all
  end

  # GET /documentaires/1
  # GET /documentaires/1.json
  def show
  end

  # GET /documentaires/new
  def new
    @documentaire = Documentaire.new
  end

  # GET /documentaires/1/edit
  def edit
  end

  # POST /documentaires
  # POST /documentaires.json
  def create
    @documentaire = Documentaire.new(documentaire_params)

    respond_to do |format|
      if @documentaire.save
        format.html { redirect_to @documentaire, notice: 'Documentaire was successfully created.' }
        format.json { render :show, status: :created, location: @documentaire }
      else
        format.html { render :new }
        format.json { render json: @documentaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentaires/1
  # PATCH/PUT /documentaires/1.json
  def update
    respond_to do |format|
      if @documentaire.update(documentaire_params)
        format.html { redirect_to @documentaire, notice: 'Documentaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @documentaire }
      else
        format.html { render :edit }
        format.json { render json: @documentaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentaires/1
  # DELETE /documentaires/1.json
  def destroy
    @documentaire.destroy
    respond_to do |format|
      format.html { redirect_to documentaires_url, notice: 'Documentaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documentaire
      @documentaire = Documentaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def documentaire_params
      params.require(:documentaire).permit(:nom, :realisateur)
    end
end

 def set_checked
    @documentaires.checked = params[:checked] == 'true' ? true : false
    @documentaires.save
    respond_to do |format|
      format.json { render json: {status: true, checked: @documentaires.checked} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documentaires
      @documentaires = documentaires.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def documentaires_params
      params.require(:documentaires).permit(:nom, :realisateur, :date, :checked)
    end

app/helpers/documentaires_helper.rb
module DocumentairesHelper
end

app/views/documentaires/_form.html.erb
<%= form_for(documentaire) do |f| %>
  <% if documentaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(documentaire.errors.count, "error") %> prohibited this documentaire from being saved:</h2>

      <ul>
      <% documentaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom %>
  </div>

  <div class="field">
    <%= f.label :realisateur %>
    <%= f.text_field :realisateur %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documentaires/edit.html.erb
<h1>Editing Documentaire</h1>

<%= render 'form', documentaire: @documentaire %>

<%= link_to 'Show', @documentaire %> |
<%= link_to 'Back', documentaires_path %>

app/views/documentaires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documentaires</h1>

<table id="documentaires-index">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Realisateur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documentaires.each do |documentaire| %>
      <tr>
        <td><%= documentaire.nom %></td>
        <td><%= documentaire.realisateur %></td>
        <td><%= link_to 'Show', documentaire %></td>
        <td><%= link_to 'Edit', edit_documentaire_path(documentaire) %></td>
        <td><%= link_to 'Destroy', documentaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/documentaires/new.html.erb
<h1>New Documentaire</h1>

<%= render 'form', documentaire: @documentaire %>

<%= link_to 'Back', documentaires_path %>

app/views/documentaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @documentaire.nom %>
</p>

<p>
  <strong>Realisateur:</strong>
  <%= @documentaire.realisateur %>
</p>

<%= link_to 'Edit', edit_documentaire_path(@documentaire) %> |
<%= link_to 'Back', documentaires_path %>