config/routes.rb
Filmsouseries::Application.routes.draw do

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	get '/logout' => 'sessions#destroy'

	get '/signup' => 'users#new'
	post '/users' => 'users#create'
end

Rails.application.routes.draw do
  resources :series
  get '/series/:id/set_checked/:checked' => 'series#set_checked'
  resources :films
  get '/films/:id/set_checked/:checked' => 'films#set_checked'
  resources :documentaires
  get '/documentaires/:id/set_checked/:checked' => 'documentaires#set_checked'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="home">
<h1>Bienvenue sur Films ou Séries</h1>
<p>Ici faites une liste des films, séries et documentaires que vous souhaitez regarder plus tard pour ne pas les oublier !<p>
<h2>Films</h2>
<ul id="films-index">
	<% @films.each do |film| %>
		<li>
			<%= link_to film.nom, film %>
			<%= check_box_tag "checked_film_#{film.id}", nil, film.checked, :'data-id' => film.id %>		
		</li>
	<% end %>
	<%= link_to 'Ajouter', new_film_path %>
</ul>

<h2>Séries</h2>
<ul id="series-index">
	<% @series.each do |series| %>
		<li>
			<%= link_to series.nom, series %>
			<%= check_box_tag "checked_series_#{series.id}", nil, series.checked, :'data-id' => series.id %>		
		</li>
	<% end %>
	<%= link_to 'Ajouter', new_series_path %>
</ul>

<h2>Documentaires</h2>
<ul id="documentaires-index">
	<% @documentaires.each do |documentaire| %>
		<li>
			<%= link_to documentaire.nom, documentaire %>
			<%= check_box_tag "checked_documentaire_#{documentaire.id}", nil, documentaire.checked, :'data-id' => documentaire.id %>		
		</li>
	<% end %>
	<%= link_to 'Ajouter', new_documentaire_path %>
</ul>
</div>