config/routes.rb
Filmsouseries::Application.routes.draw do

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	get '/logout' => 'sessions#destroy'

	get '/signup' => 'users#new'
	post '/users' => 'users#create'
end

Rails.application.routes.draw do
  resources :series
  get '/series/:id/set_checked/:checked' => 'series#set_checked'
  resources :films
  get '/films/:id/set_checked/:checked' => 'films#set_checked'
  resources :documentaires
  get '/documentaires/:id/set_checked/:checked' => 'documentaires#set_checked'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id          :integer          not null, primary key
#  nom         :string
#  realisateur :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Film < ApplicationRecord
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy, :set_checked]
  before_filter :authorize

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:nom, :realisateur)
    end
end

 def set_checked
    @film.checked = params[:checked] == 'true' ? true : false
    @film.save
    respond_to do |format|
      format.json { render json: {status: true, checked: @film.checked} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:nom, :realisateur, :date, :checked)
    end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for(film) do |f| %>
  <% if film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom %>
  </div>

  <div class="field">
    <%= f.label :realisateur %>
    <%= f.text_field :realisateur %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Films</h1>

<table id="films-index">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Realisateur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.nom %></td>
        <td><%= film.realisateur %></td>
        <td><%= link_to 'Show', film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @film.nom %>
</p>

<p>
  <strong>Realisateur:</strong>
  <%= @film.realisateur %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>