config/routes.rb
Filmsouseries::Application.routes.draw do

	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	get '/logout' => 'sessions#destroy'

	get '/signup' => 'users#new'
	post '/users' => 'users#create'
end

Rails.application.routes.draw do
  resources :series
  get '/series/:id/set_checked/:checked' => 'series#set_checked'
  resources :films
  get '/films/:id/set_checked/:checked' => 'films#set_checked'
  resources :documentaires
  get '/documentaires/:id/set_checked/:checked' => 'documentaires#set_checked'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy, :set_checked]
  before_action :authorize
  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:nom, :realisateur)
    end
end

 def set_checked
    @series.checked = params[:checked] == 'true' ? true : false
    @series.save
    respond_to do |format|
      format.json { render json: {status: true, checked: @series.checked} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:nom, :realisateur, :date, :checked)
    end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_for(series) do |f| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom %>
  </div>

  <div class="field">
    <%= f.label :realisateur %>
    <%= f.text_field :realisateur %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table id="series-index">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Realisateur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.nom %></td>
        <td><%= series.realisateur %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @series.nom %>
</p>

<p>
  <strong>Realisateur:</strong>
  <%= @series.realisateur %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>